### PR TITLE
Fixes @2x css files

### PR DESCRIPTION
**Pull request by nicolasbadia**
The image path wasn’t replaced by the high resolution version in @2x CSS files.

This PR fixes this, but as a side effect, also double the build time!

@mauritslamers: Any idea of how we could improve this ?

### CODE REVIEW

**Comment by mauritslamers** [comment]
The most time during build is spent in minification, especially cssmin. I see only a few ways we could improve the build time:

  * ensure that in a multi app build using the same version of a specific framework that framework is built only once. SproutCore specifically contains a lot of css, and minifying it costs a lot of time.
  * use different/faster libraries for minification
  * cache the built and minified css and js for globally installed frameworks on disk. I am not a fan of this, but it will reduce build times in quite a few cases. Reason to do only globally installed frameworks is that it is much more unlikely that you are intending to work on the frameworks installed globally than the ones installed in the projects frameworks directory.

**Comment by mauritslamers** [comment]
A quick search shows a few library alternatives for cssmin

  * https://github.com/ded/sqwish
  * https://github.com/css/csso 
  * https://github.com/jakubpawlowicz/clean-css (which says it is fast...)

**Comment by nicolasbadia** [comment]
Didn't though it would be because of the minification. But we could prevent having to minify both CSS version (the @2x and the normal one) by replacing the @2x URL in the minified version.

**Comment by nicolasbadia** [comment]
We could indeed also move to clean-css which I think is currently the best library for CSS minification, but I'm not sure it will be faster. You can compare the CSS libraries there: http://goalsmashers.github.io/css-minification-benchmark/

**Comment by mauritslamers** [comment]
Interesting link! Speedwise sqwish is the best by far. The question therefore is: should we go for fast or small?

**Comment by nicolasbadia** [comment]
Well I think we should add support for several minifiers. Until then are a ok with that changes ?

**Pull request merged**
