### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by nicolasbadia**

### CODE REVIEW

**Comment by mauritslamers** [comment]
I have a few remarks: If we are leaving node v0.10 behind, we don't need watchCounts or keeping track of the paths, as node v0.12 supports recursive. If we are going to drop the fsevents dep (which I think is a good idea), we also better refactor the directory watchers, and just use recursive on the framework directory.

**Comment by nicolasbadia** [comment]
That's what I started to do until I read the node doc which say that the recursive option is only supported on OS X.

**Comment by nicolasbadia** [comment]
watchCount is indeed not needed but I wanted to know how many directories were being watch for my project. Since there is no performance impact I thought it may be useful to keep it for future use...

**Comment by mauritslamers** [comment]
ok, great. Merging...

**Pull request merged**
